### ISSUE TITLE
logeplease package missing in splitio@9.2.1

### ISSUE THREAD

**Issue by Eli-Goldberg** [splitio/javascript-client#85]
Hi,
I've seen another bug about "logplease" breaking npm install but it was in version 9.2.0,
And I'm already using 9.2.1.

This still happens to me, I can't see why.
Could this issue be on my end?

I'm using node 8.1.0.

package-lock.json resolves "logplease" to:

"logplease": {
      "version": "github:nicozelaya/logplease#b4ca204f892080a2011fe3b3f3b2b1c8c72bb29c"
}

**Comment by patricioe** [comment]
Hey,

What's the issue you are seeing? We had to patch logplease  and issue a PR to the owner of the repo.

The repo you see there belongs to us.

**Comment by Eli-Goldberg** [comment]
It could by me fault somewhere, thing is it works locally but it's failing our build.

I could be related to the fact the repo is pulled from github, referring to a direct commit,
but I it's unlikely.

Here is the the build log from Bitbucket Pipelines:

module.js:487
    throw err;
    ^
Error: Cannot find module 'logplease'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/@splitsoftware/splitio/lib/utils/logger/index.js:19:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/@splitsoftware/splitio/lib/client/client.js:14:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/@splitsoftware/splitio/lib/client/node.js:3:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/@splitsoftware/splitio/lib/index.js:17:21)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/src/services/split.js:1:79)

**Comment by patricioe** [comment]
We'll investigate. Highly likely we'll have to expose it via npm package.

**Comment by patricioe** [comment]
Is this error from your local build? Or in the target machine where you are deploying?

**Comment by patricioe** [comment]
It needs git to build. We are sure it has to do with git not being available in your build system.

**Comment by Eli-Goldberg** [comment]
Thanks a lot guys !
Adding git solved the issue.

**Comment by patricioe** [comment]
Great to hear!
